print('please enter 20 number then push enter')
a1 = float(input( 'please enter number ='))
a2 = float(input('please enter number ='))
a3 = float(input('please enter number ='))
a4 = float(input('please enter number ='))
a5 = float(input('please enter number ='))
a6 = float(input('please enter number ='))
a7 = float(input('please enter number ='))
a8 = float(input('please enter number ='))
a9 = float(input('please enter number ='))
a10 = float(input('please enter number ='))
a11 = float(input('please enter number ='))
a12 = float(input('please enter number ='))
a13 = float(input('please enter number ='))
a14 = float(input('please enter number ='))
a15 = float(input('please enter number ='))
a16 = float(input('please enter number ='))
a17 = float(input('please enter number ='))
a18 = float(input('please enter number ='))
a19 = float(input('please enter number ='))
a20 = float(input('please enter number ='))
print('-------------------------------')
print('sum == ') 
x = a1+a2+a3+a4+a5+a6+a7+a8+a9+a10+a11+a12+a13+a14+a15+a16+a17+a18+a19+a20
print(x)
print('-------------------------------')
print('average ==')
z = x/20
print(z)
print('-------------------------------')
print('max = ',max(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20))
print('min = ',min(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20))

print('-------------------------------')

